### ISSUE TITLE
File handling: what measures does Rust take regarding file handling?

### ISSUE THREAD

**Issue by andymeneely** [VulnerabilityHistoryProject/mega-foss#28]
Including permissions, closing

https://cwe.mitre.org/data/definitions/378	Creation of Temporary File With Insecure Permissions
https://cwe.mitre.org/data/definitions/910	Use of Expired File Descriptor

**Comment by blaqat** [comment]
For CWE 910, I believe the borrow checker handles this. Because you cannot reuse the file after it was dropped/out of scope/changed ownership.

For creating files with insecure permissions. Rust gives you the Permissions struct ([and PermissionsExt for unix](https://doc.rust-lang.org/std/os/unix/fs/trait.PermissionsExt.html)) that needs to be applied to a created file so this is more opt in.
https://doc.rust-lang.org/std/fs/struct.Permissions.html

Otherwise for CWE 910 idiomatically you would use the external `tempfile` crate for securely creating tempfiles.

**Comment by andymeneely** [comment]
Ok so given that the `tempfile` crate exists and is actively maintained with over 50 versions - my guess is that `std` doesn't do this for you automatically. I'm going with Opt-In Measures only, and `tempfile` implements those opt-in measures.
