### ISSUE TITLE
Character encoding: what does Rust do to prevent character encoding confusion?

### ISSUE THREAD

**Issue by andymeneely** [VulnerabilityHistoryProject/mega-foss#33]
https://cwe.mitre.org/data/definitions/838	Inappropriate Encoding for Output Context

**Comment by blaqat** [comment]
The only real thing rust 'enforces' relating to encoding is that strings are gaurenteed to be valid utf8 unless opting for [std::str::from_utf8_unchecked()](https://doc.rust-lang.org/stable/std/str/fn.from_utf8_unchecked.html).
Otherwise you are usually making a byte array. Also, bytes and characters are distinct. 

For anything other than that though, rust does not handle or enforce you would have to use an external crate if one exists.

For the CWE specifically though I'd lean towards not handled by rust. Not sure that I completely understand this CWE however.

**Comment by andymeneely** [comment]
I'm going to come back to this one - there's probably some opt-in measures but it's unlikely they do this automatically. I'm reviewing UTF stuff these days for another project anyway.

**Comment by MatthewFluet** [comment]
It seems that the CWE is more than just UTF-8 encoding.

I don't think that Rust language or std library gives any particular defense (other than the guarantee that `String` and `str` are guaranteed to be UTF-8 in safe code).  One could imagine wrapper types and similar that try to enforce an encoding, but it would be more an idiom than a formal guarantee.
