### ISSUE TITLE
Refcounting: Does refcounting exist in safe Rust?

### ISSUE THREAD

**Issue by andymeneely** [VulnerabilityHistoryProject/mega-foss#34]
https://cwe.mitre.org/data/definitions/911	Improper Update of Reference Count

**Comment by blaqat** [comment]
Yes, Rust provides the [Rc type](https://doc.rust-lang.org/std/rc/struct.Rc.html) to automatically manage reference counting / multiple ownership. (As well as [Arc](https://doc.rust-lang.org/std/sync/struct.Arc.html) for muti-threaded reference counting.)

There is more information [here in the rust book](https://doc.rust-lang.org/book/ch15-04-rc.html).

**Comment by MatthewFluet** [comment]
Rust standard library references: https://doc.rust-lang.org/std/rc/index.html and https://doc.rust-lang.org/std/sync/struct.Arc.html

Reference counting (the feature) certainly exists in safe Rust.

(Improper Update of) Reference Count (the vulnerability) does not exist in safe Rust.  If you use `std::rc::Rc` and `std::sync::Arc`, then proper reference count maintenance is guaranteed by the `Clone::clone` and `Drop::drop` methods that are implemented on `std::rc::Rc` and `std::sync::Arc`. The only way to obtain a new reference to a reference count object is through `Clone::clone`, which will increment the count.  The decrement of the count will happen when a reference count object is dropped, and, by ownership, there will be no way to retain access to the reference count object after the drop.

Moreover, one cannot move a `std::rc::Rc` to another thread (because it is not `Send`), therefore, the can be no race conditions that lead to improper updates of reference counts with `std::rc::Rc`.  On the other hand, a `std::sync::Arc` is `Send` and can be moved to another thread, but uses atomic instructions to ensure proper reference count maintenance in the presence of concurrent operations.

**Comment by MatthewFluet** [comment]
It's unclear to me whether the CWE is only referring to a language's provided RC type (which, one would typically expect to be "correct") or to an RC pattern that is being implemented incorrectly for specific datatypes.  With regard to the latter, I do not believe that one can implement the RC interface without `unsafe` in Rust, so I would say that safe Rust pretty much eliminates the issue.

**Comment by andymeneely** [comment]
Agreed on this. With the assumption that `std::rc::Rc` is bug-free, I think safe rust makes this virtually impossible. 

Yeah the CWE sometimes states things like it's universal to all languages when it's kinda idiosyncratic to C/C++ world. 

Marking this one as `Virtually Impossible`. I think I'll also add a paragraph on this in the paper.
