### ISSUE TITLE
Redundant code: does Rust/Clippy do anything about code clones or other redundant code?

### ISSUE THREAD

**Issue by andymeneely** [VulnerabilityHistoryProject/mega-foss#37]
https://cwe.mitre.org/data/definitions/1071	Empty Code Block

**Comment by blaqat** [comment]
Surprisingly to me, even with pedantic clippy, I do not think redundant code is warned.

And for the CWE empty code blocks are not warned as they are considered intentional because you have to intentionally handle not-handling errors.

Rust core includes the macros `unreachable`, `todo`, or `unimplemented` to classify / show intent for blocks that otherwise would be empty. Which will all `panic` if reached, making sure developers know to come back to that area.

But no, rust/clippy does not warn for empty code blocks or generic redundant code (having two functions that do the same thing).

**Comment by andymeneely** [comment]
Potentially these are related:

clippy::empty_loop
clippy::empty_structs_with_brackets

I'm going to classify it with Opt-In Measures Only
