### ISSUE TITLE
Strings and slices: do String and str slices help with security in any way?

### ISSUE THREAD

**Issue by andymeneely** [VulnerabilityHistoryProject/mega-foss#38]
https://cwe.mitre.org/data/definitions/1046	Creation of Immutable Text Using String Concatenation

**Comment by blaqat** [comment]
Yes, the String type is meant to be the owned growable/mutable version of str in a way. `str`'s can ONLY be immutable. You can mutate a `&mut str`, but you can only change the characters inside not extend the length.

A Good analogy is:
Array `[]`, Slice `&[]`, `Vector` --> `str`, `&str`, `String`

For chaining, if you chain a `String` + `&str`, it the output takes ownership of String and reuses its buffer to append `&str` into, growing the buffer if needed.
https://doc.rust-lang.org/std/string/struct.String.html#impl-Add%3C%26str%3E-for-String

For many concatenations like in the cwe example, you should really be using `String.push_str(&str)` as it just appends to the existing String reallocating a larger buffer if it is needed like Vectors. Also similar to vectors, if you know the size of the data you are adding you should use `String::with_capacity` so it does not need to reallocate at all.
https://doc.rust-lang.org/std/string/struct.String.html#method.with_capacity

The last way to concat is using `format!("{String}{&str}")` which allocates a new String and would have similar issues to the CWE above. But format! really is more for interpolation that just string concatenation so that's to be expected.
https://doc.rust-lang.org/std/macro.format.html#

Because of `format!`, the classification could be "opt in" features. Otherwise it is "not possible" in safe rust.

**Comment by MatthewFluet** [comment]
Technically, the "array" type in Rust is the `[ty; N]` type --- a statically sized type (https://doc.rust-lang.org/reference/types/array.html).  The dynamically sized type `[ty]` is the "slice" type (https://doc.rust-lang.org/std/primitive.slice.html).  Confusingly, both `&[ty]` and `&mut [ty]` are also called "slices", though they are technically "fat pointer" references to slies.

**Comment by andymeneely** [comment]
Yeah agreed. I think that a Rust newbie or a auto-translator would simply use String to get it working, but much of std and other APIs take the `str` slice, so you'd be encouraged to move to that anyway.

I think this is an example of Discouraged via Borrow Checker. You could potentially do it "wrong", but if you're re-engineering you're going to likely go the more conservative `str` route.

Closing this unless there's more discussion. Thank you for the perspective!!
